language: r
cache: packages
sudo: false

#install:
#        - Rscript -e "install.packages(c('rmarkdown', 'revealjs'))"
r_packages:
        - rmarkdown
        - revealjs
install: 
        - echo "No install needed"

script:
        - make

deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
                branch: master


