language: r
sudo: false

#r_packages:
#        - knitr
#        - rmarkdown
#        - revealjs
          
install: 
        - echo "No install needed"
        - Rscript -e "install.packages(c('knitr', 'rmarkdown', 'revealjs'))"
        - Rscript -e "installed.packages()"

script:
        - make all

before_deploy:
        - rm .gitignore # So the presentation itself gets deployed

               
deploy:
        skip_cleanup: true
        provider: pages
        github_token: $GITHUB_TOKEN
        on:
                branch: master


