language: r
sudo: false

r_packages:
        - knitr
        - rmarkdown
        - revealjs
          
install: 
        - echo "No install needed"

script:
        - make
before_deploy:
        - ls

after_deploy:
        - ls
               
deploy:
        skip_cleanup: true
        provider: pages
        github_token: $GITHUB_TOKEN
        on:
                branch: master


