language: r
cache: packages
sudo: false

r_packages:
        - rmarkdown
        - revealjs
          
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y a2ps        
install: 
        - echo "No install needed"

script:
        - make

deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
                branch: master


