language: r
cache: packages
sudo: false

install:
        - Rscript -e "install.packages('rmarkdown')"
script:
        - make

deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
                branch: master


