language: r
sudo: required

#r_packages:
#        - knitr
#        - rmarkdown
#        - revealjs

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y a2ps ghostscript

install: 
        - echo "No install needed"
        - Rscript -e "install.packages(c('knitr', 'rmarkdown', 'revealjs'))"
        - Rscript -e "installed.packages()"

script:
        - make all

before_deploy:
        - ls

after_deploy:
        - ls
               
deploy:
        skip_cleanup: true
        provider: pages
        github_token: $GITHUB_TOKEN
        on:
                branch: master


